services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-Multistep
    deploy:
      replicas: 4
    ports:
      - "8080-8083:8080"
    environment:
      HOTEL_MONGO_URI: mongodb://mongo:27017/hotel
    depends_on:
      - mongo
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: hotel-redis
    ports:
      - "6379:6379"

    command: >
      redis-server
      --appendonly yes
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru

    volumes:
      - redis_data:/data/db

    restart: always

  mongo:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - backend

volumes:
  mongo_data:
  redis_data:

networks:
  backend:
    driver: bridge