services:
  auth-service:
    build:
      context: ./auth-service
    deploy:
      replicas: 2
#    ports:
#      - "8080:8080"
    environment:
      HOTEL_MONGO_URI: mongodb://mongo:27017/hotel
    depends_on:
      - mongo
    networks:
      - backend

  inventory-service:
    build:
      context: ./inventory-service
    deploy:
      replicas: 2
#    ports:
#      - "8081:8081"
    environment:
      HOTEL_MONGO_URI: mongodb://mongo:27017/hotel
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mongo
      - redis
    networks:
      - backend


  bookings-service:
    build:
      context: ./booking-service
    deploy:
      replicas: 2
#    ports:
#      - "8082:8082"
    environment:
      HOTEL_MONGO_URI: mongodb://mongo:27017/hotel
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mongo
      - redis
      - inventory-service
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: hotel-redis
    ports:
      - "6379:6379"

    command: >
      redis-server
      --appendonly yes
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru

    volumes:
      - redis_data:/data/db

    restart: always
    networks:
      - backend

  mongo:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - bookings-service
      - inventory-service
      - auth-service
    networks:
      - backend

volumes:
  mongo_data:
  redis_data:

networks:
  backend:
    driver: bridge