spring:
  application:
    name: hotel

  mongodb:
    uri: "${HOTEL_MONGO_URI:mongodb://localhost:27017/hotel}"

server:
  servlet:
    context-path: /api
  port: 8080
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 7.0.12